### PR TITLE
FIX #5

### LINKED ISSUE #2: v0.1.0 Testing
Write the following tests for this release 
- [x] Ensure Cloudinary exists on the client and server.
- [x] Ensure images are successfully uploaded to Cloudinary
- [x] Verify error's are successfully generated upon failed image uploads.

### LINKED ISSUE #5: 'import' and 'export' may only appear at the top level
Just try it on the clean application.
Meteor v1.2.1

### PR DESCRIPTION
**Pull request by goooseman**

### CODE REVIEW

**Comment by romans127** [comment]
So in essence using the export forced you to import Cloudinary namespace ?

**Comment by goooseman** [comment]
We can't use `export` in Metoer 1.2. Maybe because of the NodeJS version.

**Comment by romans127** [comment]
Got it,

Ecmascript is available for 1.2, but Modules is bound to 1.3 makes sense.

**Comment by romans127** [comment]
Merging now, future reference let's put it in a patch branch so it doesn't conflict with the master updates.

**Pull request merged**
